language: java
jdk:
  - oraclejdk8
env:
  matrix:
    - PROFILE=non-existant
    - PROFILE=spring5-next
addons:
  apt:
    packages:
    - oracle-java8-installer
cache:
  directories:
    - $HOME/.m2
sudo: false
install: true
script: "./mvnw clean dependency:list test -P${PROFILE} -Dsort"
